"""Bundled coats materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import coats
    coats.chrome()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def chrome(roughness=None):
    m = PbrProperties.from_dict({   'id': 'chrome',
    'name': 'chrome',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8289136787893979,
                               0.8461357050249962,
                               0.854846859663698],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.688, 0.728, 0.798]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def coat_matte(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'coat_matte',
    'name': 'coat_matte',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 0.5},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def coat_gloss(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'coat_gloss',
    'name': 'coat_gloss',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 0.12},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def metallic_coat_matte(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'metallic_coat_matte',
    'name': 'metallic_coat_matte',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 1.0, 'roughness': 0.5},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def metallic_coat_gloss(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'metallic_coat_gloss',
    'name': 'metallic_coat_gloss',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 1.0, 'roughness': 0.12},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

__all__ = ['chrome',
 'coat_gloss',
 'coat_matte',
 'metallic_coat_gloss',
 'metallic_coat_matte']
