"""Bundled glass materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import glass
    glass.glass()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def glass(color=None, roughness=None, thickness=None):
    m = PbrProperties.from_dict({   'id': 'glass',
    'name': 'glass',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.992933564381722,
                               0.9977988695523646,
                               0.9977988695523646],
                  'metalness': 0.0,
                  'roughness': 0.0,
                  'ior': 1.52,
                  'transmission': 1.0,
                  'attenuationColor': [0.984, 0.995, 0.995],
                  'attenuationDistance': 1.0,
                  'thickness': 1.0,
                  'dispersion': 0.3125},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if thickness is not None:
        m = m.override(thickness=thickness)
    return m

__all__ = ['glass']
