"""Bundled metal materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import metal
    metal.aluminum()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def aluminum(roughness=None):
    m = PbrProperties.from_dict({   'id': 'aluminum',
    'name': 'aluminum',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.916, 0.923, 0.924],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def aluminum_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'aluminum_brushed',
    'name': 'aluminum_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.916, 0.923, 0.924],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def aluminum_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'aluminum_matte',
    'name': 'aluminum_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.916, 0.923, 0.924],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def brass(roughness=None):
    m = PbrProperties.from_dict({   'id': 'brass',
    'name': 'brass',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.91, 0.778, 0.423],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.952, 0.979, 1.021]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def brass_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'brass_brushed',
    'name': 'brass_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.91, 0.778, 0.423],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.952, 0.979, 1.021]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def brass_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'brass_matte',
    'name': 'brass_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.91, 0.778, 0.423],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.952, 0.979, 1.021]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def bronze(roughness=None):
    m = PbrProperties.from_dict({   'id': 'bronze',
    'name': 'bronze',
    'source': 'gpuopen',
    'url': 'https://matlib.gpuopen.com/main/materials/all?id=74b24db8-adac-41a6-96a6-9172f72abab0',
    'license': 'MIT Public Domain',
    'values': {   'color': [   0.833819316811031,
                               0.6965824523561795,
                               0.5457185180587919],
                  'metalness': 1.0,
                  'roughness': 0.0784314,
                  'ior': 1.45,
                  'specularIntensity': 0.5,
                  'specularColor': [0.662745, 0.443137, 0.258824]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def bronze_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'bronze_brushed',
    'name': 'bronze_brushed',
    'source': 'gpuopen',
    'url': 'https://matlib.gpuopen.com/main/materials/all?id=74b24db8-adac-41a6-96a6-9172f72abab0',
    'license': 'MIT Public Domain',
    'values': {   'color': [   0.833819316811031,
                               0.6965824523561795,
                               0.5457185180587919],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'ior': 1.45,
                  'specularIntensity': 0.5,
                  'specularColor': [0.662745, 0.443137, 0.258824]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def bronze_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'bronze_matte',
    'name': 'bronze_matte',
    'source': 'gpuopen',
    'url': 'https://matlib.gpuopen.com/main/materials/all?id=74b24db8-adac-41a6-96a6-9172f72abab0',
    'license': 'MIT Public Domain',
    'values': {   'color': [   0.833819316811031,
                               0.6965824523561795,
                               0.5457185180587919],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'ior': 1.45,
                  'specularIntensity': 0.5,
                  'specularColor': [0.662745, 0.443137, 0.258824]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def copper(roughness=None):
    m = PbrProperties.from_dict({   'id': 'copper',
    'name': 'copper',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.932, 0.623, 0.522],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.982, 0.947, 0.945]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def copper_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'copper_brushed',
    'name': 'copper_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.932, 0.623, 0.522],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.982, 0.947, 0.945]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def copper_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'copper_matte',
    'name': 'copper_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.932, 0.623, 0.522],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.982, 0.947, 0.945]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def gold(roughness=None):
    m = PbrProperties.from_dict({   'id': 'gold',
    'name': 'gold',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [1.059, 0.773, 0.307],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.971, 1.018, 0.994]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def gold_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'gold_brushed',
    'name': 'gold_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [1.059, 0.773, 0.307],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.971, 1.018, 0.994]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def gold_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'gold_matte',
    'name': 'gold_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [1.059, 0.773, 0.307],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.971, 1.018, 0.994]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def silver(roughness=None):
    m = PbrProperties.from_dict({   'id': 'silver',
    'name': 'silver',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.991, 0.985, 0.974],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.994, 0.995, 0.998]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def silver_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'silver_brushed',
    'name': 'silver_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.991, 0.985, 0.974],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.994, 0.995, 0.998]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def silver_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'silver_matte',
    'name': 'silver_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.991, 0.985, 0.974],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.994, 0.995, 0.998]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def stainless(roughness=None):
    m = PbrProperties.from_dict({   'id': 'stainless',
    'name': 'stainless',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.669, 0.639, 0.598],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.789, 0.823, 0.87]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def stainless_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'stainless_brushed',
    'name': 'stainless_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.669, 0.639, 0.598],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.789, 0.823, 0.87]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def stainless_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'stainless_matte',
    'name': 'stainless_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.669, 0.639, 0.598],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.789, 0.823, 0.87]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def aluminum_anodized(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'aluminum_anodized',
    'name': 'aluminum_anodized',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.6, 0.0, 0.0],
                  'metalness': 1.0,
                  'roughness': 0.3,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

__all__ = ['aluminum',
 'aluminum_anodized',
 'aluminum_brushed',
 'aluminum_matte',
 'brass',
 'brass_brushed',
 'brass_matte',
 'bronze',
 'bronze_brushed',
 'bronze_matte',
 'copper',
 'copper_brushed',
 'copper_matte',
 'gold',
 'gold_brushed',
 'gold_matte',
 'silver',
 'silver_brushed',
 'silver_matte',
 'stainless',
 'stainless_brushed',
 'stainless_matte']
