"""Bundled metal materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import metal
    metal.aluminum()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def aluminum(roughness=None):
    m = PbrProperties.from_dict({   'id': 'aluminum',
    'name': 'aluminum',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.962127915014933,
                               0.9653593968226258,
                               0.965819868630574],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def aluminum_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'aluminum_brushed',
    'name': 'aluminum_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.962127915014933,
                               0.9653593968226258,
                               0.965819868630574],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def aluminum_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'aluminum_matte',
    'name': 'aluminum_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.962127915014933,
                               0.9653593968226258,
                               0.965819868630574],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def brass(roughness=None):
    m = PbrProperties.from_dict({   'id': 'brass',
    'name': 'brass',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9593465889662697,
                               0.8952268365504931,
                               0.6821586160863968],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.952, 0.979, 1.021]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def brass_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'brass_brushed',
    'name': 'brass_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9593465889662697,
                               0.8952268365504931,
                               0.6821586160863968],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.952, 0.979, 1.021]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def brass_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'brass_matte',
    'name': 'brass_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9593465889662697,
                               0.8952268365504931,
                               0.6821586160863968],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.952, 0.979, 1.021]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def bronze(roughness=None):
    m = PbrProperties.from_dict({   'id': 'bronze',
    'name': 'bronze',
    'source': 'gpuopen',
    'url': 'https://matlib.gpuopen.com/main/materials/all?id=74b24db8-adac-41a6-96a6-9172f72abab0',
    'license': 'MIT Public Domain',
    'values': {   'color': [   0.833819316811031,
                               0.6965824523561795,
                               0.5457185180587919],
                  'metalness': 1.0,
                  'roughness': 0.0784314,
                  'ior': 1.45,
                  'specularIntensity': 0.5,
                  'specularColor': [0.662745, 0.443137, 0.258824]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def bronze_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'bronze_brushed',
    'name': 'bronze_brushed',
    'source': 'gpuopen',
    'url': 'https://matlib.gpuopen.com/main/materials/all?id=74b24db8-adac-41a6-96a6-9172f72abab0',
    'license': 'MIT Public Domain',
    'values': {   'color': [   0.833819316811031,
                               0.6965824523561795,
                               0.5457185180587919],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'ior': 1.45,
                  'specularIntensity': 0.5,
                  'specularColor': [0.662745, 0.443137, 0.258824]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def bronze_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'bronze_matte',
    'name': 'bronze_matte',
    'source': 'gpuopen',
    'url': 'https://matlib.gpuopen.com/main/materials/all?id=74b24db8-adac-41a6-96a6-9172f72abab0',
    'license': 'MIT Public Domain',
    'values': {   'color': [   0.833819316811031,
                               0.6965824523561795,
                               0.5457185180587919],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'ior': 1.45,
                  'specularIntensity': 0.5,
                  'specularColor': [0.662745, 0.443137, 0.258824]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def copper(roughness=None):
    m = PbrProperties.from_dict({   'id': 'copper',
    'name': 'copper',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9694932227237055,
                               0.8112085757532148,
                               0.7496651069259223],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.982, 0.947, 0.945]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def copper_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'copper_brushed',
    'name': 'copper_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9694932227237055,
                               0.8112085757532148,
                               0.7496651069259223],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.982, 0.947, 0.945]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def copper_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'copper_matte',
    'name': 'copper_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9694932227237055,
                               0.8112085757532148,
                               0.7496651069259223],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.982, 0.947, 0.945]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def gold(roughness=None):
    m = PbrProperties.from_dict({   'id': 'gold',
    'name': 'gold',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.8926775272379572,
                               0.5900005962166698],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.971, 1.018, 0.994]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def gold_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'gold_brushed',
    'name': 'gold_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.8926775272379572,
                               0.5900005962166698],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.971, 1.018, 0.994]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def gold_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'gold_matte',
    'name': 'gold_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.8926775272379572,
                               0.5900005962166698],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.971, 1.018, 0.994]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def silver(roughness=None):
    m = PbrProperties.from_dict({   'id': 'silver',
    'name': 'silver',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9960333152256678,
                               0.9933771717300072,
                               0.9884829524812248],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.994, 0.995, 0.998]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def silver_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'silver_brushed',
    'name': 'silver_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9960333152256678,
                               0.9933771717300072,
                               0.9884829524812248],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.994, 0.995, 0.998]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def silver_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'silver_matte',
    'name': 'silver_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9960333152256678,
                               0.9933771717300072,
                               0.9884829524812248],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.994, 0.995, 0.998]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def nickel(roughness=None):
    m = PbrProperties.from_dict({   'id': 'nickel',
    'name': 'nickel',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8526800368272145,
                               0.8215498880219183,
                               0.7754196632585052],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.815, 0.834, 0.871]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def nickel_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'nickel_brushed',
    'name': 'nickel_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8526800368272145,
                               0.8215498880219183,
                               0.7754196632585052],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.815, 0.834, 0.871]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def nickel_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'nickel_matte',
    'name': 'nickel_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8526800368272145,
                               0.8215498880219183,
                               0.7754196632585052],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.815, 0.834, 0.871]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def stainless(roughness=None):
    m = PbrProperties.from_dict({   'id': 'stainless',
    'name': 'stainless',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8373050318261851,
                               0.8204092888324144,
                               0.7965522215794997],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.789, 0.823, 0.87]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def stainless_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'stainless_brushed',
    'name': 'stainless_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8373050318261851,
                               0.8204092888324144,
                               0.7965522215794997],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.789, 0.823, 0.87]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def stainless_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'stainless_matte',
    'name': 'stainless_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.8373050318261851,
                               0.8204092888324144,
                               0.7965522215794997],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.789, 0.823, 0.87]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def steel(roughness=None):
    m = PbrProperties.from_dict({   'id': 'steel',
    'name': 'steel',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.7547806693306308,
                               0.7438551299770171,
                               0.7313912786073086],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.765, 0.767, 0.802]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def steel_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'steel_brushed',
    'name': 'steel_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.7547806693306308,
                               0.7438551299770171,
                               0.7313912786073086],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.765, 0.767, 0.802]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def steel_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'steel_matte',
    'name': 'steel_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.7547806693306308,
                               0.7438551299770171,
                               0.7313912786073086],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.765, 0.767, 0.802]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def titanium(roughness=None):
    m = PbrProperties.from_dict({   'id': 'titanium',
    'name': 'titanium',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.6950701317088461,
                               0.6651850846308363,
                               0.6350498414533903],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.865, 0.906, 0.946]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def titanium_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'titanium_brushed',
    'name': 'titanium_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.6950701317088461,
                               0.6651850846308363,
                               0.6350498414533903],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.865, 0.906, 0.946]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def titanium_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'titanium_matte',
    'name': 'titanium_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.6950701317088461,
                               0.6651850846308363,
                               0.6350498414533903],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.865, 0.906, 0.946]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def zinc(roughness=None):
    m = PbrProperties.from_dict({   'id': 'zinc',
    'name': 'zinc',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9103256807292641,
                               0.9280187744328082,
                               0.9381370204587529],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.762, 0.833, 0.896]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def zinc_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'zinc_brushed',
    'name': 'zinc_brushed',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9103256807292641,
                               0.9280187744328082,
                               0.9381370204587529],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.762, 0.833, 0.896]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def zinc_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'zinc_matte',
    'name': 'zinc_matte',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9103256807292641,
                               0.9280187744328082,
                               0.9381370204587529],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.762, 0.833, 0.896]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def tin(roughness=None):
    m = PbrProperties.from_dict({   'id': 'tin',
    'name': 'tin',
    'source': 'physicallybased-approx',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.78, 0.8, 0.79],
                  'metalness': 1.0,
                  'roughness': 0.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.6038, 0.6383, 0.6739]},
    'textures': {}})
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def tin_brushed(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'tin_brushed',
    'name': 'tin_brushed',
    'source': 'physicallybased-approx',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.78, 0.8, 0.79],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.6038, 0.6383, 0.6739]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_brush'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def tin_matte(roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'tin_matte',
    'name': 'tin_matte',
    'source': 'physicallybased-approx',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.78, 0.8, 0.79],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'specularIntensity': 1.0,
                  'specularColor': [0.6038, 0.6383, 0.6739]},
    'textures': {'normal': 'normal.png', 'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_matte'),
    })
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def aluminum_anodized(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'aluminum_anodized',
    'name': 'aluminum_anodized',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [0.7977377330312598, 0.0, 0.0],
                  'metalness': 1.0,
                  'roughness': 0.3,
                  'specularIntensity': 1.0,
                  'specularColor': [0.91, 0.936, 0.959]},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

__all__ = ['aluminum',
 'aluminum_anodized',
 'aluminum_brushed',
 'aluminum_matte',
 'brass',
 'brass_brushed',
 'brass_matte',
 'bronze',
 'bronze_brushed',
 'bronze_matte',
 'copper',
 'copper_brushed',
 'copper_matte',
 'gold',
 'gold_brushed',
 'gold_matte',
 'nickel',
 'nickel_brushed',
 'nickel_matte',
 'silver',
 'silver_brushed',
 'silver_matte',
 'stainless',
 'stainless_brushed',
 'stainless_matte',
 'steel',
 'steel_brushed',
 'steel_matte',
 'tin',
 'tin_brushed',
 'tin_matte',
 'titanium',
 'titanium_brushed',
 'titanium_matte',
 'zinc',
 'zinc_brushed',
 'zinc_matte']
