"""Bundled paper materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import paper
    paper.corrugated_cardboard()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def corrugated_cardboard(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'corrugated_cardboard',
    'name': 'corrugated_cardboard',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Cardboard 002',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'corrugated_cardboard'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def paper(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'paper',
    'name': 'paper',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Paper 001',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'paper'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def foamboard(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'foamboard',
    'name': 'foamboard',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Styrofoam 004',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'foamboard'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

__all__ = ['corrugated_cardboard', 'foamboard', 'paper']
