"""Bundled plastic materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import plastic
    plastic.acrylic()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def acrylic(color=None, roughness=None, thickness=None):
    m = PbrProperties.from_dict({   'id': 'acrylic',
    'name': 'acrylic',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 0.0,
                  'ior': 1.4905,
                  'transmission': 1.0,
                  'thickness': 1.0,
                  'dispersion': 0.376081233546446},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if thickness is not None:
        m = m.override(thickness=thickness)
    return m

def plastic_clean(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'plastic_clean',
    'name': 'plastic_clean',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Plastic 013 A',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 0.15,
                  'ior': 1.5},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def plastic_rough(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'plastic_rough',
    'name': 'plastic_rough',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Plastic 013 A',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'plastic_rough'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def carbon_fiber(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'carbon_fiber',
    'name': 'carbon_fiber',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Fabric 004',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'carbon_fiber'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

__all__ = ['acrylic', 'carbon_fiber', 'plastic_clean', 'plastic_rough']
