"""Bundled plastic materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import plastic
    plastic.acrylic()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
import functools
import warnings
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def acrylic(color=None, roughness=None, thickness=None):
    m = PbrProperties.from_dict({   'id': 'acrylic',
    'name': 'acrylic',
    'source': 'physicallybased',
    'url': 'https://physicallybased.info/',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 0.0,
                  'ior': 1.4905,
                  'transmission': 1.0,
                  'thickness': 1.0,
                  'dispersion': 0.376081233546446},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if thickness is not None:
        m = m.override(thickness=thickness)
    return m

def plastic(color=None, roughness=None):
    m = PbrProperties.from_dict({   'id': 'plastic',
    'name': 'plastic',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Plastic 013 A',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 0.15,
                  'ior': 1.5},
    'textures': {}})
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    return m

def plastic_rough(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'plastic_rough',
    'name': 'plastic_rough',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Plastic 013 A',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / '_rough'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def plastic_fdm(color=None, roughness=None, scale=(6.4, 6.4), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'plastic_fdm',
    'name': 'plastic_fdm',
    'source': 'generated by script',
    'url': '',
    'license': 'MIT',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'},
    'texture_repeat': [0.15625, 0.15625],
    'normalize_uvs': False},
        "maps_dir": str(_ASSETS / '_fdm'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (6.4, 6.4) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation, fixed=False)
    return m

def plastic_fdm_skin(color=None, roughness=None, scale=(6.4, 6.4), rotation=45.0):
    m = PbrProperties.from_dict({
        **{   'id': 'plastic_fdm_skin',
    'name': 'plastic_fdm_skin',
    'source': 'generated by script',
    'url': '',
    'license': 'MIT',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'},
    'texture_repeat': [0.15625, 0.15625],
    'texture_rotation': 45.0,
    'normalize_uvs': False},
        "maps_dir": str(_ASSETS / '_fdm_skin'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (6.4, 6.4) or rotation != 45.0:
        m = m.scale(scale[0], scale[1], rotation=rotation, fixed=False)
    return m

def carbon_fiber(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'carbon_fiber',
    'name': 'carbon_fiber',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Fabric 004',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 1.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'carbon_fiber'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

__all__ = ['acrylic',
 'carbon_fiber',
 'plastic',
 'plastic_fdm',
 'plastic_fdm_skin',
 'plastic_rough']

# Deprecated aliases — removed in the next major.

@functools.wraps(plastic)
def plastic_clean(*args, **kwargs):
    warnings.warn(
        "plastic_clean() is deprecated, use plastic() instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    return plastic(*args, **kwargs)
