"""Bundled textile materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import textile
    textile.fabric_weave()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def fabric_weave(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'fabric_weave',
    'name': 'fabric_weave',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Fabric 060',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'fabric_weave'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def felt(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'felt',
    'name': 'felt',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Fabric 034',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.9999999999999999,
                               0.9999999999999999,
                               0.9999999999999999],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'felt'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def leather(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'leather',
    'name': 'leather',
    'source': 'ambientcg',
    'url': 'https://ambientcg.com/view?id=Leather 028',
    'license': 'CC0 1.0',
    'values': {   'color': [   0.47843137254901963,
                               0.3215686274509804,
                               0.18823529411764706],
                  'metalness': 0.0,
                  'roughness': 1.0,
                  'ior': 1.5},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'leather'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

__all__ = ['fabric_weave', 'felt', 'leather']
