"""Bundled wood materials — GENERATED by scripts/build_bundle.py.
Do not edit by hand.

    from threejs_materials import wood
    wood.ash()

Each material is a factory returning a fresh PbrProperties; the signature
exposes only the overrides that make sense: `color` (colorable; raw metals
omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),
`thickness` (transmissive).
"""
from pathlib import Path

from threejs_materials.library import PbrProperties

_ASSETS = Path(__file__).parent / "_assets"

def ash(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'ash',
    'name': 'ash',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'ash'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def beech(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'beech',
    'name': 'beech',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'beech'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def birch(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'birch',
    'name': 'birch',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'birch'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def cherry(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'cherry',
    'name': 'cherry',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'cherry'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def maple(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'maple',
    'name': 'maple',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'maple'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def mdf(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'mdf',
    'name': 'mdf',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'mdf'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def oak(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'oak',
    'name': 'oak',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'oak'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def osb(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'osb',
    'name': 'osb',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'osb'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def pine(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'pine',
    'name': 'pine',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'pine'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def spruce(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'spruce',
    'name': 'spruce',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'spruce'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

def walnut(color=None, roughness=None, scale=(1, 1), rotation=0.0):
    m = PbrProperties.from_dict({
        **{   'id': 'walnut',
    'name': 'walnut',
    'source': 'custom',
    'url': '',
    'license': '',
    'values': {'color': [1.0, 1.0, 1.0], 'metalness': 0.0, 'roughness': 1.0},
    'textures': {   'color': 'color.png',
                    'normal': 'normal.png',
                    'roughness': 'roughness.png'}},
        "maps_dir": str(_ASSETS / 'walnut'),
    })
    if color is not None:
        m = m.override(color=color)
    if roughness is not None:
        m = m.override(roughness=roughness)
    if scale != (1, 1) or rotation:
        m = m.scale(scale[0], scale[1], rotation=rotation)
    return m

__all__ = ['ash',
 'beech',
 'birch',
 'cherry',
 'maple',
 'mdf',
 'oak',
 'osb',
 'pine',
 'spruce',
 'walnut']
