"""Authoring generator for the bundled material library.

Runs the curated source recipes (needs `pip install threejs-materials[materialx]`
+ network), bakes/transforms them, writes the trimmed texture assets under
`src/threejs_materials/pbr_properties/_assets/`, and emits one module per
category (`wood.py`, `metal.py`, `coats.py`, ...) inside `pbr_properties/`.
`threejs_materials/__init__.py` re-exports them so users do
`from threejs_materials import wood; wood.ash()`.

Re-runnable / idempotent. Edit the RECIPE tunables below and re-run to curate.
Bundled materials load with NO materialx; this generator is the only part that
needs it.
"""

from __future__ import annotations

import pprint
import shutil
from pathlib import Path

import numpy as np
from fdm_layers import TILE_MM as FDM_TILE_MM
from fdm_layers import generate as fdm_generate
from PIL import Image

from threejs_materials import PbrProperties
from threejs_materials.sources import CACHE_DIR
from threejs_materials.utils import _normalize_srgb_color

RES = "1K"
PKG = Path(__file__).resolve().parent.parent / "src" / "threejs_materials"
BUNDLED = PKG / "bundled"          # legacy flat module/dir — cleaned up on run
SUB = PKG / "pbr_properties"       # category modules + shared _assets live here
ASSETS = SUB / "_assets"           # shared textures, referenced by every category module
# Category → module name. Each becomes threejs_materials/pbr_properties/<module>.py,
# re-exported from threejs_materials/__init__.py so `from threejs_materials import metal` works.
CATEGORY_MODULES = ("wood", "paper", "metal", "coats", "plastic", "glass", "textile")
# Pre-optimized wood assets (color/normal/roughness PNGs per subdir), committed
# to the repo because wood is ingested from local glTF, not a download source.
WOOD_SRC = PKG.parent.parent / "wood_src"

# --- Curation tunables (edit + re-run) -------------------------------------
LEATHER_DEFAULT_COLOR = "#7a5230"  # baked default (medium brown); leather(color=...) overrides
LEATHER_MAP_MEAN = 0.85            # brightness target for the desaturated map
PLASTIC_BASE_ROUGHNESS = 0.15      # roughness of the texture-less plastic base
COAT_MATTE_ROUGHNESS = 0.5         # roughness of the *_matte coats (matte)
COAT_GLOSS_ROUGHNESS = 0.12        # roughness of the *_gloss coats
TRANSMISSIVE_THICKNESS = 1.0       # baked default thickness (object units) for glass/acrylic
                                   #   drives volumetric refraction; overridable per call
# The FDM set is authored at a real-world scale (one tile = FDM_TILE_MM), so its
# default scale is baked with raw parametric UVs: 1 UV unit = 1 mm, giving the
# printed layer pitch on any part size. Triplanar mapping ignores this and
# normalizes by the bounding box — pass scale=(FDM_TILE_MM/bbox,) * 2 there.
FDM_PROVENANCE = {"source": "generated by script", "url": "", "license": "MIT"}
# Top/bottom skin: solid infill laid on a flat substrate, so the bead is squashed
# (k=8 → 12.5 µm relief vs the wall's 53.7) and the pitch is the extrusion width,
# not the layer height — 0.4 mm gives exactly 16 lines per tile. Glossier and
# lower-contrast than a wall; tint span shrinks with the relief, tint base rises
# to keep the map mean level with the wall's so both read the same under a tint.
# The 45° is baked as a UV rotation, not into the pixels: rotating in texture
# space keeps the tiling and the 0.4 mm pitch exact. Pass rotation=-45 for the
# bottom face, the way slicers alternate.
FDM_SKIN = {"layer_mm": 0.4, "k": 8, "grain_mm": 0.0025,
            "rough": (0.38, 0.22), "tint": (0.82, 0.10)}
FDM_SKIN_ROTATION = 45.0
# Renamed factories keep a working alias: old name -> current name. Emitted after
# __all__ so they stay out of the advertised API. Drop these at the next major.
DEPRECATED_ALIASES = {"plastic_clean": "plastic"}

# Metals that get a shiny/brushed/matte triple (scalar base + shared surface map)
METAL_FINISH_BASES: dict[str, tuple[str, str]] = {
    "aluminum": ("physicallybased", "Aluminum"),
    "brass": ("physicallybased", "Brass"),
    "bronze": ("gpuopen", "Bronze"),
    "copper": ("physicallybased", "Copper"),
    "gold": ("physicallybased", "Gold"),
    "silver": ("physicallybased", "Silver"),
    "nickel": ("physicallybased", "Nickel"),
    "stainless": ("physicallybased", "Stainless Steel"),
    "steel": ("physicallybased", "Iron"),       # bare iron ≈ raw/mild steel
    "titanium": ("physicallybased", "Titanium"),
    "zinc": ("physicallybased", "Zinc"),
}
# Standalone scalar metals (no finish triple)
METAL_STANDALONE: dict[str, tuple[str, str]] = {
    "aluminum_anodized": ("physicallybased", "Aluminum (Anodized Red)"),
    "chrome": ("physicallybased", "Chromium"),
}
# Bare metals with no source-DB entry — hand-authored. Per the to_dict
# convention: color is sRGB; specularColor is LINEAR (here converted from an
# sRGB [0.80,0.82,0.84] starting point).
HAND_AUTHORED_METALS: dict[str, dict] = {
    "tin": {
        "source": "physicallybased-approx",
        "url": "https://physicallybased.info/",
        "license": "CC0 1.0",
        "values": {
            "color": [0.78, 0.80, 0.79],
            "metalness": 1.0,
            "roughness": 0.0,
            "specularIntensity": 1.0,
            "specularColor": [0.6038, 0.6383, 0.6739],
        },
    },
}
# Shared metal surface map sets: (asset dir, source, name)
BRUSH = ("_brush", "ambientcg", "Metal 009")
MATTE = ("_matte", "ambientcg", "Metal 032")

# Plastic: scalar base + shared finish map sets, mirroring the metal
# shiny/brushed/matte triple (gold → gold_brushed → gold_matte).
PLASTIC_BASE = ("ambientcg", "Plastic 013 A")
PLASTIC_ROUGH = ("_rough", *PLASTIC_BASE)

# Own-dir textured materials: name -> (source, source_name)  [keep color+normal+roughness]
TEXTURED: dict[str, tuple[str, str]] = {
    "corrugated_cardboard": ("ambientcg", "Cardboard 002"),
    "paper": ("ambientcg", "Paper 001"),
    "foamboard": ("ambientcg", "Styrofoam 004"),
    "fabric_weave": ("ambientcg", "Fabric 060"),
    "felt": ("ambientcg", "Fabric 034"),
    "carbon_fiber": ("ambientcg", "Fabric 004"),
}
# Scalar (texture-less) materials: name -> (source, source_name)
SCALARS: dict[str, tuple[str, str]] = {
    "acrylic": ("physicallybased", "Plastic (Acrylic)"),
    "glass": ("physicallybased", "Glass (Soda-lime)"),
}

TEX_CAT = {
    "corrugated_cardboard": "paper",
    "paper": "paper",
    "foamboard": "paper",
    "fabric_weave": "textile",
    "felt": "textile",
    "carbon_fiber": "plastic",   # composite → plastic category (weave texture)
}

SURFACE_MAPS = ("normal", "roughness")
FULL_MAPS = ("color", "normal", "roughness")

_FN = {
    "physicallybased": PbrProperties.from_physicallybased,
    "ambientcg": PbrProperties.from_ambientcg,
    "gpuopen": PbrProperties.from_gpuopen,
}


def _cache_dir(source: str, name: str) -> Path:
    safe = name.lower().replace(" ", "_")
    return CACHE_DIR / f"{source}_{safe}_{RES.lower()}"


def bake(source: str, name: str) -> PbrProperties:
    return _FN[source](name, RES)


def _copy_maps(src_dir: Path, dst_dir: Path, keep: tuple[str, ...]) -> dict[str, str]:
    """Copy the kept map PNGs into dst_dir; return {field: filename}."""
    dst_dir.mkdir(parents=True, exist_ok=True)
    out = {}
    for field in keep:
        f = src_dir / f"{field}.png"
        if f.exists():
            shutil.copy2(f, dst_dir / f.name)
            out[field] = f.name
    return out


def _desaturate_normalize(src: Path, dst: Path, mean: float) -> None:
    lum = Image.open(src).convert("L")
    arr = np.asarray(lum, dtype=np.float32) / 255.0
    scaled = np.clip(arr * (mean / (arr.mean() + 1e-6)), 0, 1)
    Image.fromarray((scaled * 255).astype("uint8"), mode="L").save(dst)


def _drop_stale(values: dict, kept: tuple[str, ...]) -> dict:
    """Drop scalars whose paired map was trimmed away."""
    if "displacement" not in kept:
        values.pop("displacementScale", None)
    return values


# (name, from_dict payload sans maps_dir, asset_dir|None, accepts_color, baked|None)
# baked = {"scale": (u, v), "rotation": deg} — "rotation" optional.
Entry = tuple[str, dict, str | None, bool, dict | None]


def _payload(
    name: str,
    mat: PbrProperties,
    tex: dict[str, str],
    baked: dict | None = None,
    prov: dict[str, str] | None = None,
) -> dict:
    """``baked`` bakes a non-identity UV transform (raw parametric, mm) into the
    payload rather than calling ``.scale()``, so a default call keeps id == name."""
    p = {
        "id": name,
        "name": name,
        "source": mat.source,
        "url": mat.url,
        "license": mat.license,
        "values": _drop_stale(mat.values.to_dict(), tuple(tex)),
        "textures": tex,
    }
    p.update(prov or {})
    if baked is not None:
        u, v = baked["scale"]
        p["texture_repeat"] = [1 / u, 1 / v]
        if baked.get("rotation"):
            p["texture_rotation"] = baked["rotation"]
        p["normalize_uvs"] = False
    return p


def build() -> tuple[list[Entry], dict[str, str]]:
    out: list[Entry] = []
    cat: dict[str, str] = {}

    def add(category, name, mat, tex=None, adir=None, color=False, baked=None, prov=None):
        out.append((name, _payload(name, mat, tex or {}, baked, prov), adir, color, baked))
        cat[name] = category

    # plastics + glass scalars (colorable dielectrics). Transmissive ones get a
    # baked thickness so volumetric refraction works out of the box.
    for category, name in (("plastic", "acrylic"), ("glass", "glass")):
        m = bake(*SCALARS[name])
        if m.values.transmission:
            m.values.thickness = TRANSMISSIVE_THICKNESS
        add(category, name, m, color=True)

    # plastic — scalar base + shared finish map sets (the metal pattern).
    # bake() first so the cache is populated before _copy_maps reads it.
    rough_set = bake(*PLASTIC_BASE)
    _copy_maps(_cache_dir(*PLASTIC_BASE), ASSETS / PLASTIC_ROUGH[0], FULL_MAPS)
    def fdm_set(adir: str, **kwargs) -> PbrProperties:
        d = ASSETS / adir
        files = fdm_generate(d, **kwargs)
        return PbrProperties.create(
            id=adir, **{f"{k}_map": str(d / v) for k, v in files.items()}
        )

    walls, skin = fdm_set("_fdm"), fdm_set("_fdm_skin", **FDM_SKIN)
    pbase = rough_set.strip_maps()  # deep-copies values, so rough_set is unharmed
    pbase.values.roughness = PLASTIC_BASE_ROUGHNESS
    add("plastic", "plastic", pbase, color=True)

    ftex = {f: f"{f}.png" for f in FULL_MAPS}
    mm_true = {"scale": (FDM_TILE_MM, FDM_TILE_MM)}
    for finish, other, adir, baked, prov in (
        ("rough", rough_set, PLASTIC_ROUGH[0], None, None),
        ("fdm", walls, "_fdm", mm_true, FDM_PROVENANCE),
        ("fdm_skin", skin, "_fdm_skin",
         {**mm_true, "rotation": FDM_SKIN_ROTATION}, FDM_PROVENANCE),
    ):
        m = pbase.with_maps(other, only=FULL_MAPS)
        m.values.roughness = 1.0  # let the surface map drive roughness
        add("plastic", f"plastic_{finish}", m, dict(ftex), adir,
            color=True, baked=baked, prov=prov)

    # own-dir textured (colorable dielectrics; color+normal+roughness).
    # bake() first so the cache is populated before _copy_maps reads it.
    for name, (src, sname) in TEXTURED.items():
        mat = bake(src, sname)
        tex = _copy_maps(_cache_dir(src, sname), ASSETS / name, FULL_MAPS)
        add(TEX_CAT[name], name, mat, tex, name, color=True)

    # metals — NO color (intrinsic reflectance). shiny = base name;
    # brushed/matte share the two surface-map sets.
    brush, matte = bake(*BRUSH[1:]), bake(*MATTE[1:])
    for adir, src, sname in (BRUSH, MATTE):
        _copy_maps(_cache_dir(src, sname), ASSETS / adir, SURFACE_MAPS)
    stex = {"normal": "normal.png", "roughness": "roughness.png"}
    for base_name, (src, sname) in METAL_FINISH_BASES.items():
        add("metal", base_name, bake(src, sname))
        base = bake(src, sname)
        for finish, other, adir in (("brushed", brush, "_brush"), ("matte", matte, "_matte")):
            m = base.with_maps(other, only=SURFACE_MAPS)
            m.values.roughness = 1.0  # let the surface map drive roughness
            add("metal", f"{base_name}_{finish}", m, dict(stex), adir)
    # hand-authored metals (no source DB) — same shiny/brushed/matte triple
    for base_name, spec in HAND_AUTHORED_METALS.items():
        base = PbrProperties.from_dict({"id": base_name, "name": base_name, **spec})
        add("metal", base_name, base)
        for finish, other, adir in (("brushed", brush, "_brush"), ("matte", matte, "_matte")):
            m = base.with_maps(other, only=SURFACE_MAPS)
            m.values.roughness = 1.0
            add("metal", f"{base_name}_{finish}", m, dict(stex), adir)
    # anodized aluminum is dyed → colorable (metal); chrome is a mirror finish (coats)
    add("metal", "aluminum_anodized",
        bake(*METAL_STANDALONE["aluminum_anodized"]), color=True)
    add("coats", "chrome", bake(*METAL_STANDALONE["chrome"]))

    # coats — painted, hand-authored DIELECTRIC scalars (metalness 0)
    for name, rough in (("coat_matte", COAT_MATTE_ROUGHNESS),
                        ("coat_gloss", COAT_GLOSS_ROUGHNESS)):
        m = PbrProperties.create(id=name, color="#ffffff", metalness=0.0, roughness=rough)
        add("coats", name, m, color=True)

    # metallic coats — plated/converted METALLIC scalars (metalness 1): black
    # oxide, PVD colours, nickel/tin/zinc. Scalar mirror of coat_*.
    for name, rough in (("metallic_coat_matte", COAT_MATTE_ROUGHNESS),
                        ("metallic_coat_gloss", COAT_GLOSS_ROUGHNESS)):
        m = PbrProperties.create(id=name, color="#ffffff", metalness=1.0, roughness=rough)
        add("coats", name, m, color=True)

    # leather — one desaturated+normalized shared texture, default brown baked
    lsrc, lname = "ambientcg", "Leather 028"
    ldir = ASSETS / "leather"
    lbase = bake(lsrc, lname)  # bake first so the cache exists for the copies below
    _copy_maps(_cache_dir(lsrc, lname), ldir, SURFACE_MAPS)
    _desaturate_normalize(_cache_dir(lsrc, lname) / "color.png", ldir / "color.png", LEATHER_MAP_MEAN)
    lbase.values.color = list(_normalize_srgb_color(LEATHER_DEFAULT_COLOR)[0])
    ltex = {"color": "color.png", "normal": "normal.png", "roughness": "roughness.png"}
    add("textile", "leather", lbase, ltex, "leather", color=True)

    # wood — pre-optimized local assets, colorable (tint/stain) + textured
    if WOOD_SRC.exists():
        for wd in sorted(p for p in WOOD_SRC.iterdir() if p.is_dir()):
            slug = wd.name
            tex = {}
            for field in ("color", "normal", "roughness"):
                src = wd / f"{field}.png"
                if src.exists():
                    (ASSETS / slug).mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, ASSETS / slug / src.name)
                    tex[field] = src.name
            # neutral scalars → color map shows natural grain, roughness map drives;
            # color override tints, roughness override multiplies.
            mat = PbrProperties.create(id=slug, color="#ffffff", metalness=0.0, roughness=1.0)
            add("wood", slug, mat, tex, slug, color=True)

    return out, cat


def _ctor(payload: dict, adir: str | None) -> str:
    body = pprint.pformat(payload, indent=4, width=84, sort_dicts=False)
    if adir is None:
        return f"PbrProperties.from_dict({body})"
    return (
        f"PbrProperties.from_dict({{\n"
        f"        **{body},\n"
        f'        "maps_dir": str(_ASSETS / {adir!r}),\n'
        f"    }})"
    )


def _material_lines(
    name: str,
    payload: dict,
    adir: str | None,
    color: bool,
    baked: dict | None = None,
) -> list[str]:
    """Code lines for one factory function."""
    ctor = _ctor(payload, adir)
    has_rough = "roughness" in payload["values"]
    transmissive = payload["values"].get("transmission", 0) > 0
    default_scale = baked["scale"] if baked else (1, 1)
    default_rot = (baked or {}).get("rotation", 0.0)
    params = (
        (["color=None"] if color else [])
        + (["roughness=None"] if has_rough else [])
        + ([f"scale={default_scale}"] if adir else [])
        + ([f"rotation={default_rot}"] if adir else [])
        + (["thickness=None"] if transmissive else [])
    )
    lines = [f"def {name}({', '.join(params)}):"]
    if not params:
        lines.append(f"    return {ctor}")
        lines.append("")
        return lines
    lines.append(f"    m = {ctor}")
    if color:
        lines += ["    if color is not None:", "        m = m.override(color=color)"]
    if has_rough:
        lines += ["    if roughness is not None:", "        m = m.override(roughness=roughness)"]
    if adir:
        fixed = "" if baked is None else ", fixed=False"
        rot = "rotation" if not default_rot else f"rotation != {default_rot}"
        lines += [f"    if scale != {default_scale} or {rot}:",
                  f"        m = m.scale(scale[0], scale[1], rotation=rotation{fixed})"]
    if transmissive:
        lines += ["    if thickness is not None:", "        m = m.override(thickness=thickness)"]
    lines += ["    return m", ""]
    return lines


def emit(entries: list[Entry], cat: dict[str, str]) -> None:
    """Write one module per category into the package."""
    by_cat: dict[str, list[Entry]] = {}
    for e in entries:
        by_cat.setdefault(cat[e[0]], []).append(e)

    for category, ents in by_cat.items():
        first = ents[0][0]
        names = {e[0] for e in ents}
        aliases = {o: n for o, n in DEPRECATED_ALIASES.items() if n in names}
        lines = [
            f'"""Bundled {category} materials — GENERATED by scripts/build_bundle.py.',
            "Do not edit by hand.",
            "",
            f"    from threejs_materials import {category}",
            f"    {category}.{first}()",
            "",
            "Each material is a factory returning a fresh PbrProperties; the signature",
            "exposes only the overrides that make sense: `color` (colorable; raw metals",
            "omit it), `roughness`, `scale=(u, v)` + `rotation` degrees (textured),",
            "`thickness` (transmissive).",
            '"""',
            *(["import functools", "import warnings"] if aliases else []),
            "from pathlib import Path",
            "",
            "from threejs_materials.library import PbrProperties",
            "",
            '_ASSETS = Path(__file__).parent / "_assets"',
            "",
        ]
        for name, payload, adir, color, baked in ents:
            lines += _material_lines(name, payload, adir, color, baked)
        lines.append(f"__all__ = {pprint.pformat(sorted(names))}")
        if aliases:
            lines += ["", "# Deprecated aliases — removed in the next major."]
        for old, new in sorted(aliases.items()):
            lines += [
                "",
                f"@functools.wraps({new})",
                f"def {old}(*args, **kwargs):",
                "    warnings.warn(",
                f'        "{old}() is deprecated, use {new}() instead.",',
                "        DeprecationWarning,",
                "        stacklevel=2,",
                "    )",
                f"    return {new}(*args, **kwargs)",
            ]
        lines.append("")
        (SUB / f"{category}.py").write_text("\n".join(lines))

    mods = sorted(by_cat)
    init = [
        '"""Bundled PBR material factories, grouped by category — GENERATED.',
        "",
        "    from threejs_materials import metal   # re-exported; no `pbr_properties` needed",
        "    metal.gold_brushed()",
        '"""',
        f"from threejs_materials.pbr_properties import ({', '.join(mods)})",
        "",
        f"__all__ = {pprint.pformat(mods)}",
        "",
    ]
    (SUB / "__init__.py").write_text("\n".join(init))


def main() -> None:
    # clean legacy flat bundle, pre-subfolder top-level modules, and the subpackage
    if BUNDLED.exists():
        shutil.rmtree(BUNDLED)
    for c in CATEGORY_MODULES:
        (PKG / f"{c}.py").unlink(missing_ok=True)
    if (PKG / "_assets").exists():
        shutil.rmtree(PKG / "_assets")
    if SUB.exists():
        shutil.rmtree(SUB)
    SUB.mkdir(parents=True)
    ASSETS.mkdir(parents=True)

    entries, cat = build()
    emit(entries, cat)
    total = sum(f.stat().st_size for f in ASSETS.rglob("*") if f.is_file())
    cats = sorted(set(cat.values()))
    print(f"\nGenerated {len(entries)} materials into {len(cats)} modules: {', '.join(cats)}")
    print(f"assets total: {total / 1e6:.2f} MB @ {RES}")


if __name__ == "__main__":
    main()
